FORMAT: 1A

# ImageHostingService
An API for https://github.com/Wofho/ImageHostingService


## Categories [/categories]
### List all Categories [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "top"
        }, {
          "id": 2, "title": "trending"
        }, {
          "id": 3, "title": "newest"
        }]



## Images [/images/{id}]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

+ Model (application/json)
 
    + Body
 
            [{
            "id": "1",
            "title": "Squirrel",
            "content": "http://i.imgur.com/xHVRq7d.jpg"
            }]

### Upload an image [POST]
+ Request (application/json)




+ Response 201 (application/json)



### Retrieve an image [GET]
+ Response 200 (application/json)

    [Images][]
       
        

### Delete an image [DELETE]
+ Response 204
