FORMAT: 1A

# ImageHostingService
An API for https://github.com/Wofho/ImageHostingService


## Categories [/categories]
### List all Categories [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "top"
        }, {
          "id": 2, "title": "trending"
        }, {
          "id": 3, "title": "newest"
        }]



## Images [/images/{id}]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

+ Model (application/json)
 
    + Body
 
            [{
            "id": "1",
            "title": "Squirrel",
            "hashtag": "#nature",
            "content": "http://i.imgur.com/xHVRq7d.jpg",
            "map": "<iframe width='350' height='350' frameborder='0' style='border:0' src='https://www.google.com/maps/embed/v1/place?q=%D0%9F%D0%B0%D1%80%D0%BA%20%22%D0%91%D0%BE%D1%80%D0%B8%D1%81%D0%BE%D0%B2%D0%B0%20%D0%B3%D1%80%D0%B0%D0%B4%D0%B8%D0%BD%D0%B0%22%2C%20%D0%A1%D0%BE%D1%84%D0%B8%D1%8F%2C%20%D0%91%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D0%B8%D1%8F&key=AIzaSyDjzbtTjBZuE7Qwp9i42UNAKnM8FyzKN5c'></iframe>"
            },{
            "id": "2",
            "title": "Fountain",
            "hashtag": "#nature",
            "content": "http://i.imgur.com/SoBP6ok.jpg",
            "map": "<iframe width='350' height='350' frameborder='0' style='border:0' src='https://www.google.com/maps/embed/v1/place?q=%D0%AE%D0%B6%D0%B5%D0%BD%20%D0%BF%D0%B0%D1%80%D0%BA%2C%20%D0%A1%D0%BE%D1%84%D0%B8%D1%8F%2C%20%D0%91%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D0%B8%D1%8F&key=AIzaSyDjzbtTjBZuE7Qwp9i42UNAKnM8FyzKN5c'></iframe>"
            },{
            "id": "3",
            "title": "Seaside",
            "hashtag": "#drunk",
            "content": "http://i.imgur.com/F0PNxCC.jpg",
            "map": "<iframe width='350' height='350' frameborder='0' style='border:0' src='https://www.google.com/maps/embed/v1/place?q=%D0%91%D0%B0%D0%BB%D1%87%D0%B8%D0%BA%2C%20%D0%91%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D0%B8%D1%8F&key=AIzaSyDjzbtTjBZuE7Qwp9i42UNAKnM8FyzKN5c'></iframe>"
            }]

### Upload an image [POST]
+ Request (application/json)




+ Response 201 (application/json)

    + Headers

            Location: /images/1

    + Body

                {
                    "id": "2",
                    "title": name,
                    "content": url
                }


### Retrieve an image [GET]
+ Response 200 (application/json)

    [Images][]
       
        

### Delete an image [DELETE]
+ Response 204